### ISSUE TITLE
Source Code Files Contain CRLF Line-endings

### ISSUE THREAD

**Issue by hutson** [jonatanpedersen/git-json-merge#11]
This is similar to a previous issue, #1, filed because CRLF line-endings caused issues for *nix users using `git-json-merge`.

As noted by @james-siteclick [here](https://github.com/jonatanpedersen/git-json-merge/issues/1#issuecomment-314409512), it looks like CRLF line-endings were re-introduced in commit 0c5224482dc5bce9f48fa557f8a8894938709384.

As a result, I get the following error on macOS when git attempts to resolve a JSON conflict:

```bash
env: node\r: No such file or directory
```

**Comment by jonatanpedersen** [comment]
Oops, I drowned in notifications and missed this one. I will have a look at it...

**Comment by sibelius** [comment]
any progress on this?

**Comment by jonatanpedersen** [comment]
Published `v0.4.5`, I hope it solves this.
