### ISSUE TITLE
Data is lost after merge

### ISSUE THREAD

**Issue by mjfara** [jonatanpedersen/git-json-merge#15]
Like the title states, data seems to be lost after the merge.
Two users added/updated two different nodes, both were lost in the merge.

Here's my git output:
git pull
Auto-merging project.side
Merge made by the 'recursive' strategy.
 .gitignore                |    3 +
 project.side | 2906 ++++++++++++++++++++++++++++-----------------
 2 files changed, 1799 insertions(+), 1110 deletions(-)

.side is the file extension for this particular file, but the data is in json format.

Any ideas?

**Comment by ethyde** [comment]
Hello,

i think this is because git is not able to detect the format of a file other than by its extension.
Maybe declaring `.side` files the same as JSON files will solve the problem?

**Comment by jonatanpedersen** [comment]
I guess putting `*.side merge=json` in your `~/.gitattributes` would solve it.
