### ISSUE TITLE
Whitespace not adjustable

### ISSUE THREAD

**Issue by cold-logic** [jonatanpedersen/git-json-merge#2]
The whitespace is fixed at 4 space indenting and some of my projects use 2 space indenting. The addition of a config file that overrides the default would be a welcome update.

**Comment by jonatanpedersen** [comment]
I agree, I will work on this

**Comment by jonatanpedersen** [comment]
v0.4.0 has been released with automatic detection of indention. It works with any number of characters, and it will detect changes in indention characters as well.

The behaviour is as follows (numbers are spaces):

```
selectIndent
      given arguments of 4 as ours, 2 as base and 2 as theirs
        ✓ should return 4
      given arguments of 4 as ours, 4 as base and 2 as theirs
        ✓ should return 2
      given arguments of 4 as ours, 4 as base and 4 as theirs
        ✓ should return 4
      given arguments of 2 as ours, 4 as base and 2 as theirs
        ✓ should return 2
      given arguments of 2 as ours, 2 as base and 4 as theirs
        ✓ should return 4
      given arguments of 2 as ours, 4 as base and 4 as theirs
        ✓ should return 2
```

See tests for more details.
